### ISSUE TITLE
Unable to compile it

### ISSUE THREAD

**Issue by merajhasan88** [DoctorLai/xxd#1]
The xxd.o wont run and give me this error 'bash: ./xxd.o: cannot execute binary file: Exec format error'

So I simply ran g++ xxd.cpp to get an a.out file.

I ran it => ./a.out and terminal goes blank.

What am I doing wrong? Not a c++ programmer, just needed the hexdump for a test bench in c++. Any help would be appreciated

**Comment by DoctorLai** [comment]
Added a Makefile/README
